package resource.tools;


import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EValidator;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.util.EObjectValidator;
import org.eclipse.xtext.XtextPackage;
import org.eclipse.xtext.XtextStandaloneSetup;
import org.eclipse.xtext.impl.XtextPackageImpl;

import emf.resource.tools.ResourceTool;

public class XtextResourceTool extends ResourceTool {
	
	public XtextResourceTool(){
		super(XtextResourceTool.class.getName());
		XtextPackageImpl.init();
		initializeValidator();
		injector = new XtextStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	protected void initializeValidator(){
		super.initializeValidator();
		EObjectValidator validator = new EObjectValidator();
	    EValidator.Registry.INSTANCE.put(XtextPackage.eINSTANCE, validator);
	}
	
	public void process(String workspace) {
		//the input file should be generated by using 
		//git log --topo-order --pretty=format:"%H %P" --parents  -M -C --cc --decorate=full --all > ~/commit_topology.txt
		String xTextLocation = workspace+"/model.xtext";
		String outputPath = workspace+"/model.xt";
		String outputPathValidated = workspace+"/model.xt";
		String extension = "xt";

		Resource resource = loadResourceFromXtext(workspace,xTextLocation,true);
		storeResourceContents(resource.getContents(), outputPath, extension);
		Resource fromXMI = loadResourceFromXMI(outputPath, extension);
//	    validateResource(fromXMI);
		storeResourceContents(fromXMI.getContents(), outputPathValidated, extension);

	}
	
	public void initializeDB(String dbName) {
		EPackage[] epackages = new EPackage[] { XtextPackage.eINSTANCE };
		super.initializeDB(dbName, epackages);
	}
	
	

}
